# Nhập 2 số từ bàn phím
a = float(input("Nhập số a: "))
b = float(input("Nhập số b: "))
print("\n===== KẾT QUẢ TÍNH TOÁN =====")
print("Tổng a + b =", a + b)
print("Hiệu a - b =", a - b)
print("Tich a * b =", a * b)
print("Thương a / b =", a / b)
print("Chia lấy dư a % b =", a % b)
print("Luỹ thừa a ** b =", a ** b)
print("\n===== THỨ TỰ ƯU TIÊN =====")
print("a + b * 2 =", a + b * 2)
print("(a + b) * 2 =", (a + b) * 2)
print("a ** 2 + b ** 2 =", a ** 2 + b ** 2)
